# This is an Azure DevOps Pipeline defined in YAML.
# The pipeline is designed to build Docker images, push them to Azure ACR and Docker Hub, validate Terraform configurations, and deploy AKS clusters.

# Here, the pipeline specifies which virtual machine image to use for its jobs.
pool:
  vmImage: ubuntu-latest  # Use the latest Ubuntu image for the virtual machine.

# Define a series of variables that will be used throughout the pipeline.
variables:
  - name: DEV_ENVIRONMENT
    value: delano  # Name of the development environment.
  - name: azureDockerRegistryServiceConnection
    value: 'docker_sociosync'  # Service connection for Azure Docker Registry.
  - name: dockerHubServiceConnection
    value: 'DockerHubServiceConnection'  # Service connection for Docker Hub.
  - name: imageRepositoryAzure
    value: 'socio-sync'  # Repository name in Azure (names should be lowercase due to Docker's naming standard).
  - name: imageRepositoryDockerHub
    value: 'kingmaven/socio-sync'  # Repository name in Docker Hub (username can remain mixed-case).
  - name: dockerfilePath
    value: '$(System.DefaultWorkingDirectory)/Dockerfile'  # Path to the Dockerfile.
  - name: tag
    value: '$(Build.BuildId)'  # Use the build ID as a tag for the Docker image.

# The first stage of the pipeline. This builds and pushes a Docker image to Azure Container Registry (ACR).
stages:
  - stage: BuildAndPushToACR
    displayName: Build and push Docker image to ACR
    jobs:
      - job: BuildAndPushToACR
        displayName: Build and Push to Azure ACR
        steps:
          - task: Docker@2
            displayName: Build and push an image to Azure ACR
            inputs:
              command: 'buildAndPush'
              repository: $(imageRepositoryAzure)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(azureDockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

# The second stage. This builds and pushes a Docker image to Docker Hub.
  - stage: BuildAndPushToDockerHub
    displayName: Build and push Docker image to Docker Hub
    jobs:
      - job: BuildAndPushToDockerHub
        displayName: Build and Push to Docker Hub
        steps:
          - task: Docker@2
            displayName: Build and push an image to Docker Hub
            inputs:
              command: 'buildAndPush'
              repository: $(imageRepositoryDockerHub)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerHubServiceConnection)
              tags: |
                $(tag)
                latest

# The third stage. This validates Terraform configurations and publishes some artifacts.
  - stage: TerraformValidate
    jobs:
      - job: TerraformValidateJob
        continueOnError: false  # If this job fails, don't continue to the next steps.
        steps:
          # Publishing Terraform manifests.
          - task: PublishPipelineArtifact@1
            displayName: Publish Terraform Artifacts
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/terraform-manifests'
              artifact: 'terraform-manifests-out'
              publishLocation: 'pipeline'
          # Publishing Kubernetes manifests.
          - task: PublishPipelineArtifact@1
            displayName: Publish Kube-Manifest Artifacts
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/kube-manifests'
              artifact: 'kube-manifests-out'
              publishLocation: 'pipeline'
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
              backendServiceArm: 'terraform_storage'
              backendAzureRmResourceGroupName: 'terraform-storage-rg'
              backendAzureRmStorageAccountName: 'terraformstatedelano'
              backendAzureRmContainerName: 'tfstatefiles'
              backendAzureRmKey: 'aks-terraform.tfstate'
          - task: TerraformCLI@0
            displayName: Terraform Validate
            inputs:
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
              allowTelemetryCollection: false

# The final stage. This deploys Azure Kubernetes Service (AKS) clusters.
  - stage: DeployAKSClusters
    jobs:
      - deployment: DeployDevAKSCluster
        displayName: DeployDevAKSCluster
        pool:
          vmImage: 'ubuntu-latest'
        environment: $(DEV_ENVIRONMENT)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadSecureFile@1
                  displayName: Download SSH Key
                  name: sshkey
                  inputs:
                    secureFile: 'aks-terraform-devops-ssh-key-ububtu.pub'
                - task: TerraformTaskV4@4
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
                    backendServiceArm: 'capstone-svc-conn'
                    backendAzureRmResourceGroupName: 'terraform-storage-rg'
                    backendAzureRmStorageAccountName: 'terraformstatedelano'
                    backendAzureRmContainerName: 'tfstatefiles'
                    backendAzureRmKey: 'aks-$(DEV_ENVIRONMENT).tfstate'
                    allowTelemetryCollection: false
                - task: TerraformTaskV4@4
                  inputs:
                    provider: 'azurerm'
                    command: 'plan'
                    workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
                    environmentServiceNameAzureRM: 'capstone-svc-conn'
                    commandOptions: '-var ssh_public_key=$(sshkey.secureFilePath) -var environment=$(DEV_ENVIRONMENT) -out $(Pipeline.Workspace)/terraform-manifests-out/$(DEV_ENVIRONMENT)-$(Build.BuildId).out'
                    allowTelemetryCollection: false
                - task: TerraformTaskV4@4
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
                    environmentServiceNameAzureRM: 'capstone-svc-conn'
                    commandOptions: '$(Pipeline.Workspace)/terraform-manifests-out/$(DEV_ENVIRONMENT)-$(Build.BuildId).out'
                    allowTelemetryCollection: false

