apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nextjs-app"
  labels:
    app: "nextjs-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nextjs-app"
  template:
    metadata:
      labels:
        app: "nextjs-app"
    spec:
      containers:
      - name: nextjs-container
        image: acrrg01.azurecr.io/nextjs-app1:latest
        ports:
        - containerPort: 3000
