apiVersion: apps/v1
kind: Deployment
metadata:
  name: "socio-sync-app"
  labels:
    app: "socio-sync-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "socio-sync-app"
  template:
    metadata:
      labels:
        app: "socio-sync-app"
    spec:
      containers:
      - name: socio-sync-container
        image: delanocapstone.azurecr.io/socio-sync
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: acr-auth

