apiVersion: v1
kind: Service
metadata:
  labels:
    app: "socio-sync-app"
  name: "socio-sync-app"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: "socio-sync-app"
  sessionAffinity: None
  type: LoadBalancer
